# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 验证技术博客@神秘人
subtitle: 人的智慧不用就会枯萎。
description: 在人生中最艰难的是选择。
keywords: 验证达人
author: 神秘人
language: zh_CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://275244143.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: static/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  hljs: true # Add this line!
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: aria

# Hexo local search
search:
  path: search.xml
  field: all

# Hexo feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '



# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:275244143/275244143.github.io.git
  branch: master

# 配置版权
post_copyright:
  enable: true 
  author: 275244143@qq.com(神秘人)
  copyright_text: 作者拥有版权，请注明出处转载。

# 共享按钮
shareto: true

donate:
  enable: true 
  qqpay_qr: /img/qqpay.png

# hexo-admin authentification
admin:
  username: 275244143@qq.com
  password_hash: $2a$10$zgRXlOpDSNVcUL1bSOZI6.MQq76XQNweXkQYzYP22DUBWbdzdsbDS
  secret: 275244143@qq.com
  deployCommand: 'sh ./admin_script/hexo-generate.sh'

# Security
##
encrypt:
  enable: true
